### ISSUE TITLE
update package  dependencies

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-fieldtype#1]
Hello,

I played around with the plugin fieldtypes and came across that the devDependencies are little outdated. Especially babel would be great getting updated then further development in cloning this repo would be easier.

**Comment by DominikAngerer** [comment]
Working on a switch to use vue-cli-3: https://github.com/storyblok/storyblok-fieldtype/pull/3

**Comment by DominikAngerer** [comment]
Update is now merged: https://github.com/storyblok/storyblok-fieldtype/pull/3
